{
    'name': 'Hagbes Employee Registration',
    'version': '1.2.0',
    'depends': ['base', 'hr', 'analytic', 'hagbes_org_chart', 'web', 'mail', 'hagbes_approval_workflow'],
    'sequence':'1',
    'author': '@Hagbes Software Team',
    'category': 'Human Resources',
    'description': """
    Filter Department and Job Position based on selected Company and Department respectively.
    """,
    'data': [

        'security/security.xml',
        'security/ir.model.access.csv',
        'views/hr_employee_views.xml',
        'views/override_employee_menu.xml',
        'data/resignation_cron_job.xml',
        'views/upload_the_resident_id.xml',
        'reports/employee_private_report_template.xml',
        'reports/employee_id_card.xml',
        'views/hr_employee_public_viewsi.xml',
        'views/report.xml',
        'views/hr_address.xml',
        'views/branch.xml',
        'views/auto_create.xml',
        'views/res_users_form.xml',
        'views/family_status_view.xml',
        'views/guarantee_view.xml',
        'views/requerd_fileds_view.xml',
        'views/sms_wizard_views.xml',
        'views/auto_emp_id.xml',
        'views/employment_type_view.xml',
        'views/force_password_change_template.xml',
        # 'views/my_profile_access.xml',
        'views/resignation_views.xml',
        'data/ir_sequence_data.xml',
        'views/employee_clearance.xml',
         'views/web_login_template.xml',
         'views/remark_wizard_view.xml',
    ],
    # 'post_init_hook': 'post_init_hook',
    # 'post_init_hook': 'assign_parent_hook',
    'assets': {
        'web.assets_backend': [
            'hagbes_employee_registration/static/src/js/hide_org_chart.js',
            # 'hagbes_employee_registration/static/src/js/hr_retirement_menu.js',
            # 'hagbes_employee_registration/static/src/js/hide_managers_group.js',
            # 'hagbes_employee_registration/static/src/js/force_password_change.js',
        ],
    },
    'installable': True,
}
