
{
    'name': 'Hagbes Financial Reports',
    'version': '18.0.1.3.3',
    'category': 'Accounting',
    'summary': "Odoo 18 Accounting Financial Reports,Dynamic Accounting Reports, Dynamic Financial Reports,Dynamic Report Odoo18, Odoo18,Financial Reports, Odoo18 Accounting,Accounting, Odoo Apps",
    'description': "This module creates dynamic Accounting General Ledger, Trial"
                   "Balance, Balance Sheet, Profit and Loss, Cash Book, Partner"
                   "Ledger, Aged Payable, Aged Receivable, Bank book and Tax"
                   "Reports in Odoo 18 community edition, Reporting, Odoo18 Accounting, odoo18 reporting, odoo18, odoo18 accounts reports",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'depends': ['hagbes_accounting_kit'],
    'data': [
        'security/ir.model.access.csv',
        'views/accounting_report_views.xml',
        'report/trial_balance.xml',
        'report/general_ledger_templates.xml',
        'report/financial_report_template.xml',
        'report/partner_ledger_templates.xml',
        'report/financial_reports_views.xml',
        'report/balance_sheet_report_templates.xml',
        'report/bank_book_templates.xml',
        'report/aged_payable_templates.xml',
        'report/aged_receivable_templates.xml',
        'report/tax_report_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hagbes_financial_reports/static/src/xml/general_ledger_report.xml',
            'hagbes_financial_reports/static/src/xml/trial_balance_report.xml',
            'hagbes_financial_reports/static/src/xml/cash_flow_report.xml',
            'hagbes_financial_reports/static/src/xml/bank_book_report.xml',
            'hagbes_financial_reports/static/src/xml/profit_loss_report.xml',
            'hagbes_financial_reports/static/src/xml/balance_sheet_report.xml',
            'hagbes_financial_reports/static/src/xml/partner_ledger_report.xml',
            'hagbes_financial_reports/static/src/xml/aged_payable_report.xml',
            'hagbes_financial_reports/static/src/xml/aged_receivable_report.xml',
            'hagbes_financial_reports/static/src/xml/tax_report_report.xml',
            'hagbes_financial_reports/static/src/css/dynamic_report.css',
            'hagbes_financial_reports/static/src/js/general_ledger_report.js',
            'hagbes_financial_reports/static/src/js/trial_balance_report.js',
            'hagbes_financial_reports/static/src/js/cash_flow_report.js',
            'hagbes_financial_reports/static/src/js/bank_book_report.js',
            'hagbes_financial_reports/static/src/js/profit_loss_report.js',
            'hagbes_financial_reports/static/src/js/balance_sheet_report.js',
            'hagbes_financial_reports/static/src/js/partner_ledger_report.js',
            'hagbes_financial_reports/static/src/js/aged_payable_report.js',
            'hagbes_financial_reports/static/src/js/aged_receivable_report.js',
            'hagbes_financial_reports/static/src/js/tax_report.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
