{
    'name': 'Hagbes Fleet Managements',
    'version': '18.0.1.1.0',
    'category': 'Fleet',
    'summary': 'Vehicle fleet management with assignment and maintenance tracking',
    'depends': [
        'base',
        'fleet',
        'hr',
        'mail',
        'sms',
        'hagbes_approval_workflow',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'security/multi_branch_rules.xml',
        'security/fleet_requisition_rules.xml',
        'security/approval_visibility_rules.xml',
        'security/default_fleet_menu_security.xml',
        'data/ir_sequence_data.xml',
        'data/fleet_approval_flows.xml',
        'data/ir_cron.xml',
        'data/fleet_kpi_cron.xml',
        'views/hr_employee_views.xml',
        'views/fleet_config_settings_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/fleet_utilization_report_views.xml',
        'views/fleet_availability_report_views.xml',
        'views/fleet_analytics_report_views.xml',
        'views/fleet_dashboard_views.xml',
        'views/fleet_driver_kpi_views.xml',
        'views/fleet_vehicle_assign_views.xml',
        'views/fleet_maintenance_views.xml',
        'views/fleet_trip_views.xml',
        'views/fleet_requisition_reject_wizard_views.xml',
        'views/fleet_requisition_views.xml',
        'views/fleet_allocation_views.xml',
        'views/fleet_trip_log_views.xml',
        'views/fleet_trip_gps_views.xml',
        'views/fleet_discrepancy_views.xml',
        'views/fleet_vehicle_status_log_views.xml',
        'views/fleet_allocation_append_views.xml',
        'wizard/fleet_trip_actual_wizard_view.xml',
        'wizard/fleet_checkup_wizard_view.xml',
        'views/fleet_menu.xml',
        'reports/fleet_requisition_report.xml',
        'reports/fleet_trip_summary_report.xml',
        'reports/fleet_utilization_pdf_report.xml',
        'reports/fleet_availability_pdf_report.xml',
        'reports/fleet_analytics_pdf_reports.xml',
    ],
    'installable': True,
    'application': True,
    'post_init_hook': 'post_init_hook',
    # 'assets': {
    #     'web.assets_backend': [
    #         'hagbes_fleet/static/src/css/fleet_layout_fix.css',
    #     ],
    # },
}
