{
    'name': 'Hagbes Workshop Management',
    'version': '18.0.1.1.0',
    'summary': 'Manage workshop materials and approvals',
    'author': 'Hagbes',
    'category': 'Operations',
    'depends': ['base', 'product', 'uom', 'hr', 'mail', 'sale_management', 'sale_stock', 'hagbes_sales_branch_pos', 'event', 'hagbes_approval_workflow'],
    'license': 'LGPL-3',
    'data': [
        'views/mrcv_views.xml',
        'views/mrv_views.xml',
        'views/workshop_vehicle_views.xml',
        'views/workshop_views.xml',
        'views/view_vehicle_category.xml',
        'views/view_vehicle_make.xml',
        'views/view_workshop_accessory.xml',
        'views/pm_chart_views.xml',
        'views/workshop_partner_views.xml',
        'views/menu.xml',
        'data/ir_sequence_data.xml',
        'security/workshop_security.xml',
        'security/workshop_security_rules.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': True,
}
