from odoo import models, fields, api, _
from datetime import date, timedelta
from odoo.exceptions import UserError
import logging
from calendar import monthrange


_logger = logging.getLogger(__name__)
class HrLeaveAllocation(models.Model):
    _inherit = 'hr.leave.allocation'

    year_2_balance = fields.Float(string="Year -2 Leave")
    year_1_balance = fields.Float(string="Year -1 Leave")
    current_year_balance = fields.Float(string="Current Year Leave")
    _sql_constraints = [
        ('duration_check',
         "CHECK((allocation_type='regular' AND number_of_days >= 0) OR (allocation_type != 'regular'))",
         "Regular allocations can have 0 or more days."),
    ]

    active = fields.Boolean(default=True)
    is_monthly_accrual = fields.Boolean(
        string="Monthly Accrual",
        default=False,
        readonly=True,
        help="Indicates this allocation was generated by the monthly accrual process."
    )
    approval_request_id = fields.Many2one(
        "approval.request", string="Approval Request", readonly=True
    )
    state = fields.Selection(selection_add=[
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected')
    ])
    step_progress = fields.Html(string="Approval Progress", compute='_compute_step_progress')
    can_approve = fields.Boolean(
        string="Can Approve",
        compute="_compute_can_approve",
        store=False
    )
    branch_id = fields.Many2one(
        'account.analytic.account',
        string="Branch",
        compute="_compute_branch_id",
        store=True,
        readonly=False,
    )
    number_of_days = fields.Float(
        string="number of days",
        compute='_compute_total_balance',
        store=True
    )


    @api.depends('year_2_balance', 'year_1_balance', 'current_year_balance')
    def _compute_total_balance(self):
        for rec in self:
            rec.number_of_days = rec.year_2_balance + rec.year_1_balance + rec.current_year_balance

    def write(self, vals):
        res = super().write(vals)
        if 'year_2_balance' in vals or 'year_1_balance' in vals or 'current_year_balance' in vals:
            for rec in self:
                rec.number_of_days = rec.year_2_balance + rec.year_1_balance + rec.current_year_balance
        return res

    @api.depends('employee_id', 'employee_id.job_id', 'employee_id.job_id.analytic_account_id')
    def _compute_branch_id(self):
        for rec in self:
            rec.branch_id = rec.employee_id.job_id.analytic_account_id.id if rec.employee_id and rec.employee_id.job_id and rec.employee_id.job_id.analytic_account_id else False

    @api.model
    def get_logged_in_user_balances(self):
        """Return the current logged-in user's year-based leave balances."""
        user = self.env.user
        employee = self.env['hr.employee'].search([('user_id', '=', user.id)], limit=1)
        if not employee:
            return {'year_2': 0, 'year_1': 0, 'current': 0, 'total': 0}

        data = self.get_yearly_allocation_data(employee.id)
        return data

    @api.model
    def fields_get(self, allfields=None, attributes=None):
        res = super(HrLeaveAllocation, self).fields_get(allfields, attributes)
        current_year = fields.Date.context_today(self).year
        if 'year_2_balance' in res:
            res['year_2_balance']['string'] = f"{current_year - 2} Balance"
        if 'year_1_balance' in res:
            res['year_1_balance']['string'] = f"{current_year - 1} Balance"
        if 'current_year_balance' in res:
            res['current_year_balance']['string'] = f"{current_year} Balance"
        return res
    @api.depends("approval_request_id", "approval_request_id.approver_ids")
    def _compute_can_approve(self):
        uid = self.env.user.id
        for allocation in self:
                allocation.approval_request_id._compute_current_approvers()

                approvers = allocation.approval_request_id.approver_ids.mapped("id")
                allocation.can_approve = (
                        allocation.state not in ("approved", "rejected") and uid in approvers
                )

    def custom_monthly_accrual_cron(self):
        """Monthly accrual:
        - New employees: compute full balances from hire date
        - Existing employees: increment current year balance only
        """
        today = self.env.context.get('simulate_today', fields.Date.today())
        employees = self.env['hr.employee'].sudo().search([('active', '=', True)])
        annual_leave_type = self.env['hr.leave.type'].sudo().search([('name', '=', 'Annual Leave')], limit=1)
        if not annual_leave_type:
            return True

        LEAVE_YEAR_START = 2  # Feb

        for employee in employees:
            hire_date = employee.hired_date or today
            hire_year, hire_month, hire_day = hire_date.year, hire_date.month, hire_date.day

            # Check if employee already has a monthly accrual allocation
            allocation = self.sudo().search([
                ('employee_id', '=', employee.id),
                ('holiday_status_id', '=', annual_leave_type.id),
                ('is_monthly_accrual', '=', True)
            ], limit=1)

            # --- New employee: compute yearly balances from hire date ---
            if not allocation:
                year_2_balance = 0.0
                year_1_balance = 0.0
                current_year_balance = 0.0
                monthly_accruals = []

                accrual_year = hire_year
                accrual_month = hire_month
                while (accrual_year < today.year) or (accrual_year == today.year and accrual_month <= today.month):
                    years_since_hire = accrual_year - hire_year
                    yearly_leave = 16 + 0.5 * years_since_hire

                    # Partial first month
                    if accrual_year == hire_year and accrual_month == hire_month:
                        days_in_month = monthrange(hire_year, hire_month)[1]
                        days_worked = days_in_month - hire_day + 1
                        monthly_rate = yearly_leave / 12 * (days_worked / days_in_month)
                    else:
                        monthly_rate = yearly_leave / 12

                    monthly_accruals.append({
                        'year': accrual_year,
                        'month': accrual_month,
                        'monthly_rate': monthly_rate
                    })

                    # Next month
                    accrual_month += 1
                    if accrual_month > 12:
                        accrual_month = 1
                        accrual_year += 1

                # Split balances by leave year Feb1-Jan31
                for m in monthly_accruals:
                    leave_year = m['year'] if m['month'] >= LEAVE_YEAR_START else m['year'] - 1
                    if leave_year == today.year - 2:
                        year_2_balance += m['monthly_rate']
                    elif leave_year == today.year - 1:
                        year_1_balance += m['monthly_rate']
                    elif leave_year == today.year:
                        current_year_balance += m['monthly_rate']

                total_balance = year_2_balance + year_1_balance + current_year_balance
                added_this_month = monthly_accruals[-1]['monthly_rate'] if monthly_accruals else 0.0

                # Create allocation
                allocation = self.sudo().create({
                    'employee_id': employee.id,
                    'holiday_status_id': annual_leave_type.id,
                    'year_2_balance': year_2_balance,
                    'year_1_balance': year_1_balance,
                    'current_year_balance': current_year_balance,
                    'number_of_days': total_balance,
                    'allocation_type': 'regular',
                    'date_from': today,
                    'is_monthly_accrual': True
                })
                allocation.sudo().action_validate()

                # Record history
                self.env['hr.leave.accrual.history'].create({
                    'employee_id': employee.id,
                    'allocation_id': allocation.id,
                    'year_2_balance': year_2_balance,
                    'year_1_balance': year_1_balance,
                    'current_year_balance': current_year_balance,
                    'added_this_month': added_this_month,
                    'total_balance': total_balance,
                    'accrual_date': today,
                    'note': f"Monthly accrual for {today.strftime('%B %Y')} (new employee)"
                })

            # --- Existing employee: increment current year only ---
            else:
                years_since_hire = today.year - hire_year
                yearly_leave = 16 + 0.5 * years_since_hire

                # Partial first month check (only if employee hired this month)
                if today.year == hire_year and today.month == hire_month:
                    days_in_month = monthrange(hire_year, hire_month)[1]
                    days_worked = days_in_month - hire_day + 1
                    monthly_rate = yearly_leave / 12 * (days_worked / days_in_month)
                else:
                    monthly_rate = yearly_leave / 12

                allocation.sudo().write({
                    'current_year_balance': allocation.current_year_balance + monthly_rate,
                    'number_of_days': allocation.year_2_balance + allocation.year_1_balance + allocation.current_year_balance + monthly_rate
                })

                self.env['hr.leave.accrual.history'].sudo().create({
                    'employee_id': employee.id,
                    'allocation_id': allocation.id,
                    'year_2_balance': allocation.year_2_balance,
                    'year_1_balance': allocation.year_1_balance,
                    'current_year_balance': allocation.current_year_balance,
                    'added_this_month': monthly_rate,
                    'total_balance': allocation.year_2_balance + allocation.year_1_balance + allocation.current_year_balance,
                    'accrual_date': today,
                    'note': f"Monthly accrual for {today.strftime('%B %Y')} (increment)"
                })

        return True

    def expire_old_allocations_cron(self):
        """Yearly expire leave balances based on leave year Feb1-Jan31, rotate balances, and store history."""
        today = self.env.context.get('simulate_today', date.today())
        allocations = self.sudo().search([('holiday_status_id.name', '=', 'Annual Leave')])

        LEAVE_YEAR_START = 2  # Feb
        LEAVE_YEAR_END = 1  # Jan

        for alloc in allocations:
            employee = alloc.employee_id

            # Determine leave years for rotation
            current_year = today.year
            # Leave year for Year-2 is always the leave year that ended last year
            year_2_leave_year = current_year - 2
            year_1_leave_year = current_year - 1
            current_leave_year = current_year
            expired_year = (current_year - 1) - 2  # Example: if 2026 → expired_year = 2023
            # --- Expire Year-2 balance even if 0, to rotate correctly ---
            self.env['hr.leave.expiry.history'].sudo().create({
                'employee_id': employee.id,
                'allocation_id': alloc.id,
                'expired_year': expired_year,
                'expired_balance': alloc.year_2_balance,
                'expiry_date': today,
            })

            # Rotate balances
            alloc_sudo = alloc.sudo()
            alloc_sudo.year_2_balance = alloc_sudo.year_1_balance  # Year-1 → Year-2
            alloc_sudo.year_1_balance = alloc_sudo.current_year_balance  # Current → Year-1
            alloc_sudo.current_year_balance = 0  # Reset current year for new accrual

            # Update total
            alloc_sudo.number_of_days = (
                    alloc_sudo.year_2_balance +
                    alloc_sudo.year_1_balance +
                    alloc_sudo.current_year_balance
            )

    @api.model
    def get_yearly_allocation_data(self, employee_id):
        """
        Return the balances: year2, year1, current, total
        for a given employee based on validated allocations.
        """
        allocations = self.search([
            ('employee_id', '=', employee_id),
            ('state', '=', 'validate'),
            ('holiday_status_id.name', '=', 'Annual Leave')
        ])

        year_2 = sum(a.year_2_balance for a in allocations)
        year_1 = sum(a.year_1_balance for a in allocations)
        current = sum(a.current_year_balance for a in allocations)
        total = year_2 + year_1 + current

        return {
            'year_2': year_2,
            'year_1': year_1,
            'current': current,
            'total': total
        }


    def deduct_leave_days(self, leave, total_days_to_deduct):
        """Deduct days from allocations for the given leave and record history."""
        allocations = self.search([
            ('employee_id', '=', leave.employee_id.id),
            ('holiday_status_id', '=', leave.holiday_status_id.id),
            ('state', '=', 'validate')
        ], order='create_date asc')

        remaining = total_days_to_deduct

        for alloc in allocations:
            if remaining <= 0:
                break

            # Capture BEFORE balances
            before_balances = {
                'year_2': alloc.year_2_balance,
                'year_1': alloc.year_1_balance,
                'current': alloc.current_year_balance,
                'total': alloc.year_2_balance + alloc.year_1_balance + alloc.current_year_balance,
            }

            deduction = 0.0

            # Deduct Year-2 → Year-1 → Current
            for field in ['year_2_balance', 'year_1_balance', 'current_year_balance']:
                balance = getattr(alloc, field)
                if remaining <= 0:
                    break
                if remaining <= balance:
                    setattr(alloc, field, balance - remaining)
                    deduction += remaining
                    remaining = 0
                else:
                    setattr(alloc, field, 0)
                    deduction += balance
                    remaining -= balance

            # Update total number_of_days
            alloc.number_of_days = alloc.year_2_balance + alloc.year_1_balance + alloc.current_year_balance

            # Capture AFTER balances
            after_balances = {
                'year_2': alloc.year_2_balance,
                'year_1': alloc.year_1_balance,
                'current': alloc.current_year_balance,
                'total': alloc.year_2_balance + alloc.year_1_balance + alloc.current_year_balance,
            }

            # Create deduction history
            self.env['hr.leave.deduction.history'].create({
                'leave_id': leave.id,
                'employee_id': leave.employee_id.id,
                'allocation_id': alloc.id,
                'year_2_before': before_balances['year_2'],
                'year_1_before': before_balances['year_1'],
                'current_before': before_balances['current'],
                'total_before': before_balances['total'],
                'deducted_days': deduction,
                'year_2_after': after_balances['year_2'],
                'year_1_after': after_balances['year_1'],
                'current_after': after_balances['current'],
                'total_after': after_balances['total'],
            })

        return remaining

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        for rec in records:
            # Only handle manual allocations (employee requests)
            if not rec.is_monthly_accrual:
                rec.state = 'pending'
                try:
                    rec.sudo().action_submit()  # sudo to bypass base.group_user restriction
                except Exception as e:
                    rec.message_post(
                        body=f"Approval submission failed: {str(e)}",
                        message_type="notification"
                    )
        return records
    def action_submit(self):
        self.ensure_one()
        if self.state == 'pending' and self.approval_request_id:
            raise UserError("This allocation has already been submitted for approval.")

        flow = self.env['approval.flow'].search([
            ('request_model_id.model', '=', 'hr.leave.allocation'),
            ('active', '=', True),
            ('company_id', '=', self.employee_company_id.id)
        ], limit=1)

        if not flow:
            raise UserError("No approval flow defined for Allocation!")

        first_step = self.env['approval.step'].search([
            ('flow_id', '=', flow.id)
        ], order='sequence asc', limit=1)

        if not first_step:
            raise UserError("No steps defined for this approval flow.")

        approval_req = self.env['approval.request'].create({
            'flow_id': flow.id,
            'res_model': self._name,
            'module_name': 'allocation',
            'res_id': self.id,
            'current_step_id': first_step.id,
            'status': 'pending',
        })

        self.write({
            'state': 'pending',
            'approval_request_id': approval_req.id
        })

        approval_req.process_action()

        self.message_post(
            body="Allocation Request submitted for approval",
            message_type="notification",
            subtype_xmlid="mail.mt_note"
        )

    def action_approve(self, comment=''):
        self.ensure_one()
        if not self.approval_request_id:
            raise UserError("No approval request linked to this allocation.")

        self.approval_request_id.with_context(action_type='approve', comment=comment).process_action()
        self._sync_state_from_approval()

        if self.state == 'approved':
            # Set state to 'validate' — this makes it count toward balance
            self.write({'state': 'approved'})

            # --- Always add to current year balance ---
            today = fields.Date.today()
            LeaveType = self.env['hr.leave.type']
            annual_leave_type = LeaveType.search([('name', '=', 'Annual Leave')], limit=1)
            if not annual_leave_type:
                raise UserError("Annual Leave type not found.")

            # Always add to current year, regardless of hire date
            year_2_add = 0.0
            year_1_add = 0.0
            current_add = self.number_of_days  # ← Always add to current year

            # --- Apply accrual update ---
            self._apply_accrual_update(
                employee=self.employee_id,
                annual_leave_type=annual_leave_type,
                year_2_add=year_2_add,
                year_1_add=year_1_add,
                current_add=current_add,
                accrual_date=today,
                note=f"Added via approved allocation request (ID: {self.id})"
            )

            # Trigger recompute of leave balances
            # self.employee_id.invalidate_recordset(['virtual_remaining_leaves'])
            self.holiday_status_id.invalidate_recordset()

    def action_reject(self, comment=''):
        self.ensure_one()
        try:
            if not self.approval_request_id:
                raise UserError("No approval request linked to this allocation.")

            self.approval_request_id.with_context(
                action_type='reject', comment=comment
            ).process_action()
            self._sync_state_from_approval()

            if self.state == 'rejected':
                self.write({'state': 'refuse'})

            return {"success": True}

        except (UserError, Exception) as e:
            return {"success": False, "error": str(e)}

    def _sync_state_from_approval(self):
        if not self.approval_request_id:
            return
        status = self.approval_request_id.status
        if status == 'approved':
            self.state = 'approved'
        elif status == 'rejected':
            self.state = 'rejected'
        elif status == 'pending':
            self.state = 'pending'
        else:
            self.state = 'draft'

    def _compute_step_progress(self):
        for rec in self:
            rec.step_progress = rec.approval_request_id.step_progress if rec.approval_request_id else "<span>No approval steps yet.</span>"

    def _check_approval_update(self, state):
        """Bypass Odoo's default approval security checks because we use a custom approval flow."""
        return True

    def _apply_accrual_update(self, employee, annual_leave_type, year_2_add=0.0, year_1_add=0.0, current_add=0.0,
                              accrual_date=None, note=""):
        """
        Apply accrual update: add days to year-wise balances and record in accrual history.
        Used by both monthly cron and approved allocation requests.
        """
        accrual_date = accrual_date or fields.Date.today()

        # --- Get or create allocation record ---
        allocation = self.search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', annual_leave_type.id),
        ], limit=1)

        if not allocation:
            allocation = self.create({
                'employee_id': employee.id,
                'holiday_status_id': annual_leave_type.id,
                'year_2_balance': 0.0,
                'year_1_balance': 0.0,
                'current_year_balance': 0.0,
                'number_of_days': 0.0,
                'allocation_type': 'regular',
                'date_from': fields.Date.today(),
                'state': 'validate',  # Start as approved
            })

        # --- Capture BEFORE balances ---
        before_year_2 = allocation.year_2_balance
        before_year_1 = allocation.year_1_balance
        before_current = allocation.current_year_balance
        before_total = before_year_2 + before_year_1 + before_current

        # --- Add new days ---
        new_year_2 = before_year_2 + year_2_add
        new_year_1 = before_year_1 + year_1_add
        new_current = before_current + current_add
        total_add = year_2_add + year_1_add + current_add

        # --- Update allocation ---
        allocation.write({
            'year_2_balance': new_year_2,
            'year_1_balance': new_year_1,
            'current_year_balance': new_current,
            'number_of_days': before_total + total_add,
        })

        # --- Record in accrual history ---
        self.env['hr.leave.accrual.history'].create({
            'employee_id': employee.id,
            'allocation_id': allocation.id,
            'year_2_balance': new_year_2,
            'year_1_balance': new_year_1,
            'current_year_balance': new_current,
            'added_this_month': total_add,
            'total_balance': new_year_2 + new_year_1 + new_current,
            'accrual_date': accrual_date,
            'note': note or f"Added {total_add} days via {'monthly accrual' if not note else 'manual allocation'}",
        })

        return allocation